title: Hello, Tech HR
description: > # this means to ignore newlines until "baseurl:"
  I'd like to talk about HR management for Developers(I call it TechHR)
  Actually, I've worked as a developer for 10years. Now, I'm working in
  Developer Competency team(so weired) and I love to make the environment
  for developers.  
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://namojo.github.io" # 비어있는 값을 채우세요

github-pages: 228  # 또는 현재 GitHub Pages가 사용하는 버전
jekyll: 3.9.3      # GitHub Pages와 호환되는 Jekyll 버전

plugins: # plugins_dir 대신 plugins 사용
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
future: true # 미래 날짜 포스트 허용
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Andy Cho # add your name
author-img: andy.jpg # add your photo
about-author: I am Professional Engineer from SamsungSDS. # add description
twitter: namojo # add your Twitter handle
facebook: namojo # add your Facebook handle
github: namojo # add your Github handle
linkedin: 남호-조-46062756 # add your Linkedin handle
email: chonamho@gmail.com # add your Email address

# Disqus
discus-identifier: namojo # add your discus identifier

# Tracker
## analytics: # Google Analytics

# Build Settings
markdown: kramdown
paginate: 8
paginate_path: "/page/:num"

#exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "vendor"]

theme: jekyll-theme-minimal
